### ISSUE TITLE
AndrOSC adds quotation marks around OSC arguments

### ISSUE THREAD

**Issue by ia85** [ahmetkizilay/AndrOSC#1]
Hi,
Tried the app, the interface is great and simple

But OSC messages sent from AndrOSC reach as the default (/push , /button , etc..)
and the OSC message doesn't go through.

ive used your other app - quickOSC , it was great,
ill be happy to see this one working as well.

Best

**Comment by ahmetkizilay** [comment]
what is your OSC receiving application? From what I understand your application is unable to read the arguments of the osc message.

I would be happy to look into it if you could tell me more about your set up.

**Comment by ia85** [comment]
Receiving app is VPT7.
it works perfect with QuickOsc.

I had another look now, here are all the details

With AndrOSC - OSC message are received with VPT, i see them come in.
but all the numbers are with " ".

i wrote on Ander OSC : fullscreen 1,
and the message i get on the receiving app is : fullscreen "1"

See attached images.

so i guess thats the problem and the " " needs to be removed somehow ?
any ideas?

btw, i donated & rated last week, dont know if you sew it.

thanks!

**Comment by ahmetkizilay** [comment]
hello,
I see, so you get strings as opposed to numbers. One thing I notice is that you don't have a forward slash in front of fullscreen. Do you get a different output when you change your message to '/fullscreen 1'?

Thank you so much for your donation and your feedback! I will buy me a sandwich when Google redirects the money to my account :)

**Comment by ia85** [comment]
I think he fwd slash is there .. look again  :-)

i also tried it with a few messages  , all with fwd slash , and numbers
came with " ".

see image below

any ideas ? does ANDR work for you ?
its strange, because QuickOSC works perfect.

anyway the app is called VPT7 (win)

[image: Inline image 1]

**Comment by ahmetkizilay** [comment]
I am pretty sure the cause of problem is that the OSC message arguments are sent to your application as string types while you expect them to be integers or floats. I checked that in qOSC I am converting messages to integers or floats before sending them as a part of the OSC.

I fixed the code and published an update. Keep an eye on the Play Store to download the latest version when it is available. Let me know whether of not the update fixes your problem.

**Comment by ia85** [comment]
Will do.
Thanks man !!!

**Comment by ia85** [comment]
Downloaded the new ver, it works great!
big thanks.
ill sure give it a 5 star rating + another donation!

hope to see more great apps from you.

Best,
Imri

**Comment by ahmetkizilay** [comment]
I am glad the update worked for you.
thank you so much for your support. I really appreciate it!
