### ISSUE TITLE
Unable to set negative values for sliders

### ISSUE THREAD

**Issue by riban-bw** [ahmetkizilay/AndrOSC#2]
It would be advantageous to be able to use negative values in for the slider ranges. An example is controlling the transport speed in Ardour which accepts values from -8 to +8, representing speeds in forward and reverse directions.

**Comment by ahmetkizilay** [comment]
Thanks for your feedback. It looks it is impossible to set negative values.
The fix for it is trivial. I will release an update in a couple of hours.

**Comment by ahmetkizilay** [comment]
issue fixed with 2bd5e3ce0b25a497cbad2e6ba6de5997d7c1aa9c.
uploaded this version on the Play Store. It should be available to download in a couple of hours
